using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;

namespace GeneratePDFUsingGeneratePDFMigraDoc
{
    public class PdfReportMigraDocService
    {
    public byte[] GenerateReport(List<ReportData> reports)
        {
            var document = new Document();

            foreach (var data in reports)
            {
                var section = document.AddSection();
                section.PageSetup.PageFormat = PageFormat.Letter;
                section.PageSetup.TopMargin = Unit.FromCentimeter(2);
                section.PageSetup.BottomMargin = Unit.FromCentimeter(2);
                section.PageSetup.LeftMargin = Unit.FromCentimeter(2.5);
                section.PageSetup.RightMargin = Unit.FromCentimeter(2.5);

                var title = section.AddParagraph(data.Title);
                title.Format.Font.Name = "Arial";
                title.Format.Font.Size = 18;
                title.Format.Font.Bold = true;
                title.Format.SpaceAfter = Unit.FromCentimeter(0.5);

                var subTitle = section.AddParagraph($"Generated By: {data.GeneratedBy}");
                subTitle.Format.Font.Name = "Arial";
                subTitle.Format.Font.Size = 12;
                subTitle.Format.Font.Color = Colors.DarkGray;
                subTitle.Format.SpaceAfter = Unit.FromCentimeter(1);

                var table = section.AddTable();
                table.Borders.Color = Colors.LightGray;
                table.Borders.Width = 0.5;
                table.TopPadding = 5;
                table.BottomPadding = 5;

                table.AddColumn(Unit.FromCentimeter(1.5));
                table.AddColumn(Unit.FromCentimeter(2.5));
                table.AddColumn(Unit.FromCentimeter(3.0));
                table.AddColumn(Unit.FromCentimeter(7.0));
                table.AddColumn(Unit.FromCentimeter(2.5));

                var headerRow = table.AddRow();
                headerRow.HeadingFormat = true;
                headerRow.Format.Font.Name = "Arial";
                headerRow.Format.Font.Size = 11;
                headerRow.Format.Font.Bold = true;
                headerRow.Shading.Color = Color.FromRgb(230, 230, 250);

                headerRow.Cells[0].AddParagraph("ID");
                headerRow.Cells[0].Format.Alignment = ParagraphAlignment.Center;

                headerRow.Cells[1].AddParagraph("Status");
                headerRow.Cells[2].AddParagraph("Category");
                headerRow.Cells[3].AddParagraph("Description");

                headerRow.Cells[4].AddParagraph("Amount");
                headerRow.Cells[4].Format.Alignment = ParagraphAlignment.Right;

                if (data.Items != null)
                {
                    bool isAlternate = false;
                    foreach (var item in data.Items)
                    {
                        var row = table.AddRow();
                        row.Format.Font.Name = "Arial";
                        row.Format.Font.Size = 10;
                        row.VerticalAlignment = VerticalAlignment.Center;

                        if (isAlternate)
                        {
                            row.Shading.Color = Color.FromRgb(249, 249, 249);
                        }

                        row.Cells[0].AddParagraph(item.Id);
                        row.Cells[0].Format.Alignment = ParagraphAlignment.Center;

                        row.Cells[1].AddParagraph(item.Status);
                        row.Cells[2].AddParagraph(item.Category);
                        row.Cells[3].AddParagraph(item.Description);

                        row.Cells[4].AddParagraph(item.Amount);
                        row.Cells[4].Format.Alignment = ParagraphAlignment.Right;

                        isAlternate = !isAlternate;
                    }
                }
            }

            var renderer = new PdfDocumentRenderer()
            {
                Document = document
            };

            renderer.RenderDocument();

            using var stream = new MemoryStream();
            renderer.PdfDocument.Save(stream, false);
            return stream.ToArray();
        }
    }
}