using PdfSharp;
using PdfSharp.Drawing;
using PdfSharp.Drawing.Layout;
using PdfSharp.Pdf;

namespace GeneratePDFUsingPdfSharp
{
    public class PdfReportService
    {
        public byte[] GenerateReport(List<ReportData> reports)
        {
            using var document = new PdfDocument();

            var titleFont = new XFont("Arial", 18, XFontStyleEx.Bold);
            var headerFont = new XFont("Arial", 12, XFontStyleEx.Bold);
            var regularFont = new XFont("Arial", 12, XFontStyleEx.Regular);

            var headerBgBrush = new XSolidBrush(XColor.FromArgb(230, 230, 250));
            var borderPen = XPens.Black;

            var headerFormat = new XStringFormat
            {
                LineAlignment = XLineAlignment.Center,
                Alignment = XStringAlignment.Near
            };

            foreach (var data in reports)
            {
                PdfPage page = document.AddPage();
                page.Size = PageSize.Letter;

                using XGraphics gfx = XGraphics.FromPdfPage(page);
                var textFormatter = new XTextFormatter(gfx);

                XUnit margin = XUnit.FromPoint(40);
                double yPosition = 50;
                double tableWidth = page.Width.Point - (margin.Point * 2);
                double colWidth = tableWidth / 5;
                double headerRowHeight = 25;

                gfx.DrawString(data.Title, titleFont, XBrushes.Black, new XPoint(margin.Point, yPosition));
                yPosition += 25;

                gfx.DrawString($"Generated By: {data.GeneratedBy}", regularFont, XBrushes.Gray, new XPoint(margin.Point, yPosition));
                yPosition += 40;

                double tableStartY = yPosition - 18;

                var rowHeights = new List<double>();
                double totalTableHeight = headerRowHeight;

                if (data.Items != null)
                {
                    foreach (var item in data.Items)
                    {
                        double maxH = headerRowHeight;
                        maxH = Math.Max(maxH, MeasureHeight(gfx, item.Id, regularFont, colWidth));
                        maxH = Math.Max(maxH, MeasureHeight(gfx, item.Description, regularFont, colWidth));
                        maxH = Math.Max(maxH, MeasureHeight(gfx, item.Category, regularFont, colWidth));
                        maxH = Math.Max(maxH, MeasureHeight(gfx, item.Status, regularFont, colWidth));
                        maxH = Math.Max(maxH, MeasureHeight(gfx, item.Amount, regularFont, colWidth));

                        double finalRowHeight = maxH + 10;
                        rowHeights.Add(finalRowHeight);
                        totalTableHeight += finalRowHeight;
                    }
                }

                var path = new XGraphicsPath();
                path.AddRoundedRectangle(margin.Point, tableStartY, tableWidth, totalTableHeight, 15, 15);

                var state = gfx.Save();
                gfx.IntersectClip(path);

                gfx.DrawRectangle(headerBgBrush, margin.Point, tableStartY, tableWidth, headerRowHeight);

                for (int i = 1; i < 5; i++)
                {
                    double lineX = margin.Point + (i * colWidth);
                    gfx.DrawLine(borderPen, lineX, tableStartY, lineX, tableStartY + totalTableHeight);
                }

                string[] headers = { "ID", "Description", "Category", "Status", "Amount" };
                for (int i = 0; i < 5; i++)
                {
                    var rect = new XRect(margin.Point + (i * colWidth) + 5, tableStartY, colWidth - 10, headerRowHeight);
                    gfx.DrawString(headers[i], headerFont, XBrushes.Black, rect, headerFormat);
                }

                double currentY = tableStartY + headerRowHeight;
                gfx.DrawLine(borderPen, margin.Point, currentY, margin.Point + tableWidth, currentY);

                if (data.Items != null)
                {
                    for (int i = 0; i < data.Items.Count; i++)
                    {
                        var item = data.Items[i];
                        double rH = rowHeights[i];

                        double idH = MeasureHeight(gfx, item.Id, regularFont, colWidth);
                        double descH = MeasureHeight(gfx, item.Description, regularFont, colWidth);
                        double catH = MeasureHeight(gfx, item.Category, regularFont, colWidth);
                        double statH = MeasureHeight(gfx, item.Status, regularFont, colWidth);
                        double amtH = MeasureHeight(gfx, item.Amount, regularFont, colWidth);

                        textFormatter.DrawString(item.Id, regularFont, XBrushes.Black, new XRect(margin.Point + 5, currentY + ((rH - idH) / 2), colWidth - 10, idH));
                        textFormatter.DrawString(item.Description, regularFont, XBrushes.Black, new XRect(margin.Point + colWidth + 5, currentY + ((rH - descH) / 2), colWidth - 10, descH));
                        textFormatter.DrawString(item.Category, regularFont, XBrushes.Black, new XRect(margin.Point + (2 * colWidth) + 5, currentY + ((rH - catH) / 2), colWidth - 10, catH));
                        textFormatter.DrawString(item.Status, regularFont, XBrushes.Black, new XRect(margin.Point + (3 * colWidth) + 5, currentY + ((rH - statH) / 2), colWidth - 10, statH));
                        textFormatter.DrawString(item.Amount, regularFont, XBrushes.Black, new XRect(margin.Point + (4 * colWidth) + 5, currentY + ((rH - amtH) / 2), colWidth - 10, amtH));

                        currentY += rH;
                        gfx.DrawLine(borderPen, margin.Point, currentY, margin.Point + tableWidth, currentY);
                    }
                }

                gfx.Restore(state);
                gfx.DrawPath(borderPen, path);
            }

            using var stream = new MemoryStream();
            document.Save(stream, false);
            return stream.ToArray();
        }

        private double MeasureHeight(XGraphics gfx, string text, XFont font, double maxWidth)
        {
            if (string.IsNullOrEmpty(text)) return font.Height;

            var words = text.Split(' ');
            double currentWidth = 0;
            int lines = 1;

            foreach (var word in words)
            {
                double wordWidth = gfx.MeasureString(word + " ", font).Width;
                if (currentWidth + wordWidth > maxWidth - 10)
                {
                    lines++;
                    currentWidth = wordWidth;
                }
                else
                {
                    currentWidth += wordWidth;
                }
            }
            return lines * font.Height;
        }
    }
}
